name: Unit tests

on: [push, pull_request]
env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  build-and-unit-test:
    name: Test unit-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run unit tests
        shell: bash
        run: ./tests/run_unit_tests.sh

  clippy_check:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v4
     - name: Run Clippy
       run: cargo clippy --all-targets --all-features
